import React, { useState, useEffect } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { useOverlayBackHandler } from '../../hooks/useOverlayBackHandler';
import { joinGroupWithPassCode } from '../../services/groupInviteService';
import { X, Key, ArrowRight, RefreshCw, ShieldCheck } from 'lucide-react';
import toast from 'react-hot-toast';

interface JoinGroupByCodeModalProps {
  isOpen: boolean;
  onClose: () => void;
  onJoined?: (groupId: string) => void;
  initialCode?: string;
}

export const JoinGroupByCodeModal: React.FC<JoinGroupByCodeModalProps> = ({
  isOpen,
  onClose,
  onJoined,
  initialCode = '',
}) => {
  const { currentUser, userProfile } = useAuth();
  useOverlayBackHandler(isOpen, onClose);

  const [code, setCode] = useState(initialCode);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (initialCode) {
      setCode(initialCode.toUpperCase());
    }
  }, [initialCode]);

  if (!isOpen) return null;

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    let val = e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g, '');
    if (val.length > 12) val = val.slice(0, 12);
    setCode(val);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!currentUser || submitting) return;

    const trimmedCode = code.trim().toUpperCase();
    if (!trimmedCode) {
      toast.error('Please enter a group pass code.');
      return;
    }

    setSubmitting(true);
    try {
      const res = await joinGroupWithPassCode(trimmedCode, currentUser, userProfile);
      toast.success(`Successfully joined ${res.groupName}! 🎉`);
      onJoined?.(res.groupId);
      onClose();
      setCode('');
    } catch (err: any) {
      toast.error(err.message || 'Invalid or expired group code.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
      <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm" onClick={onClose} />

      <div className="relative w-full max-w-md bg-slate-900 border border-slate-800 rounded-3xl shadow-2xl overflow-hidden z-10 my-auto p-6 space-y-5">
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-400 flex items-center justify-center">
              <Key className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">Join Private Group</h2>
              <p className="text-[11px] text-slate-400">Enter a secure CT invite pass code</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 text-slate-400 hover:text-white rounded-lg">
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-300 mb-2">
              Invite Pass Code
            </label>
            <div className="relative">
              <input
                type="text"
                value={code}
                onChange={handleInputChange}
                placeholder="e.g. CT-7K4P9X"
                maxLength={12}
                autoFocus
                required
                className="w-full bg-slate-950 border border-slate-800 focus:border-amber-500/50 rounded-2xl px-4 py-3.5 text-base sm:text-lg font-mono font-bold tracking-widest text-amber-300 placeholder-slate-600 focus:outline-none uppercase"
              />
            </div>
            <p className="text-[11px] text-slate-500 mt-2 flex items-center gap-1">
              <ShieldCheck className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
              <span>Pass codes are case-insensitive and generated by group owners.</span>
            </p>
          </div>

          <div className="pt-3 flex items-center justify-end gap-3 border-t border-slate-800">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl text-xs font-semibold"
            >
              Cancel
            </button>

            <button
              type="submit"
              disabled={submitting || !code.trim()}
              className="px-6 py-2.5 bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 disabled:opacity-50 text-slate-950 font-extrabold text-xs rounded-xl shadow-lg flex items-center gap-2 transition-all"
            >
              {submitting ? (
                <RefreshCw className="w-4 h-4 animate-spin" />
              ) : (
                <>
                  <span>Join Group</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
